# -----------------------
# 1) Сборочный этап
# -----------------------
FROM maven:3.8.5-openjdk-17 AS builder
WORKDIR /app

# Копируем только pom.xml и загружаем зависимости offline
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Копируем исходники и собираем jar (пропускаем тесты)
COPY src src
RUN mvn clean package -DskipTests -B

# -----------------------
# 2) Рантайм-этап
# -----------------------
FROM eclipse-temurin:17-jre
WORKDIR /app

# Копируем готовый Jar из предыдущего этапа
COPY --from=builder /app/target/*.jar app.jar

# Открываем порт
EXPOSE 8080

# Запускаем приложение
ENTRYPOINT ["java","-jar","app.jar"]